# Generated by Django 3.0.2 on 2020-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airscrape', '0002_auto_20200210_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bestbuy_url',
            field=models.URLField(max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='frys_url',
            field=models.URLField(max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_url',
            field=models.URLField(max_length=512, null=True, unique=True),
        ),
    ]
