# Generated by Django 3.0.2 on 2020-02-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airscrape', '0003_auto_20200210_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'store')},
        ),
    ]
