# Generated by Django 3.0 on 2020-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airscrape', '0003_auto_20200213_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
