# Generated by Django 3.0 on 2020-02-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airscrape', '0005_auto_20200213_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='walmart_url',
            field=models.URLField(max_length=512, null=True, unique=True),
        ),
    ]
